

init:
  seed: 42


data:
  train:
    name: 
    hq_img_path: 
    ann_path: 
    hq_prompt_path: 
    null_text_ratio:


  val:
    eval_list: [satext_lv3]

    realtext:
      lq_img_path: /mnt/dataset1/text_restoration/tair_published/real_text/LQ
      hq_img_path: /mnt/dataset1/text_restoration/tair_published/real_text/HQ
      ann_path: /mnt/dataset1/text_restoration/tair_published/real_text/realtext_ann.json
      vlm_captioner: llava_13b
      vlm_caption_path: /mnt/dataset1/text_restoration/100K/text_prompt/test/realtext
      val_num_img: 847

    satext_lv3:
      lq_img_path: /mnt/dataset1/text_restoration/SAMText_test_degradation/lv3
      hq_img_path: /mnt/dataset1/text_restoration/100K/test
      ann_path: /mnt/dataset1/text_restoration/100K/test/dataset.json
      vlm_captioner: llava_13b
      vlm_caption_path: /mnt/dataset1/text_restoration/100K/text_prompt/test/satext_lv3
      val_num_img: 1000
  
    satext_lv2:
      lq_img_path: /mnt/dataset1/text_restoration/SAMText_test_degradation/lv2
      hq_img_path: /mnt/dataset1/text_restoration/100K/test
      ann_path: /mnt/dataset1/text_restoration/100K/test/dataset.json
      val_num_img: 1000

    satext_lv1:
      lq_img_path: /mnt/dataset1/text_restoration/SAMText_test_degradation/lv1
      hq_img_path: /mnt/dataset1/text_restoration/100K/test
      ann_path: /mnt/dataset1/text_restoration/100K/test/dataset.json
      val_num_img: 1000

    # choose from [gt, pred_tsm, pred_vlm, null]
    text_cond_prompt: pred_vlm
    
    negative_prompt:
    save_prompts: True
    sample_times: 1
    guidance_scale: 1.0
    start_point: lr
    latent_tiled_size: 64
    latent_tiled_overlap: 24
    upscale: 4
    process_size: 512
    num_inference_steps: 40
    align_method: adain




model:
  noise_scheduler:
    weighting_scheme:
    logit_mean: 
    logit_std: 
    mode_scale:
    precondition_outputs: 

  dit:
    name: 
    resolution: 
    use_gtprompt: 
    text_condition:
      # caption_style: tag
      caption_style: descriptive

  ts_module:
    name:


ckpt:
  init_path:
    vae: preset/models/stable-diffusion-3.5-medium
    noise_scheduler: preset/models/stable-diffusion-3.5-medium
    tokenizer: preset/models/stable-diffusion-3.5-medium
    text_encoder: preset/models/stable-diffusion-3.5-medium
    dit: preset/models/dit4sr/dit4sr_q
    ts_module: preset/models/testr/totaltext_testr_R_50_polygon.pth
  resume_path:
    dit:
    ts_module: 




train:
  stage: 
  model: []
  lr: []
  finetune: []
  batch_size: 
  num_workers: 
  num_train_epochs:
  max_train_steps: 
  mixed_precision: 'fp16'
  lr_scheduler: 
  lr_warmup_steps: 
  lr_num_cycles: 
  lr_power: 
  max_grad_norm: 
  set_grads_to_none: 
  gradient_checkpointing:
  gradient_accumulation_steps: 
  scale_lr: 
  use_8bit_adam: 
  ocr_loss_weight: 
  

val:
  val_every_step:


save:
  output_dir: ./result_val
  checkpointing_steps: 


log:
  tracker: 
    report_to: wandb 
    key: e32eed0c2509bf898b850b0065ab62345005fb73
    project_name: cvpr26_tair_extension
    server: 20
    gpu: 1
    msg:
  log_dir: logs
