accelerate launch --config_file multi-gpu.yaml train/train_dit4sr.py \
    --pretrained_model_name_or_path="preset/models/stable-diffusion-3.5-medium" \
    --output_dir="./experiments/dit4sr" \
    --root_folders="preset/datasets/train_datasets" \
    --mixed_precision="fp16" \
    --learning_rate=5e-5 \
    --train_batch_size=8 \
    --gradient_accumulation_steps=1 \
    --null_text_ratio=0.2 \
    --dataloader_num_workers=0 \
    --checkpointing_steps=10000 